# Generated by Django 3.2.7 on 2022-07-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=70)),
                ('destination', models.CharField(max_length=70)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
